Added OnOpen and OnClose params for container
NebulousCloud/helix pull request #397
Opened 2023-02-24 01:00 UTC by jopnine

Added a call for OnOpen and OnClose in order to make containers interactions more customizable.

2023-02-24 09:59 UTC, garytate requested changes

2023-02-24 09:59 UTC, garytate commented on plugins/containers/entities/entities/ix_container.lua
> +			local def = ix.container.stored[self:GetModel():lower()]
```suggestion
			local definition = ix.container.stored[self:GetModel():lower()]
			
```

2023-02-24 09:59 UTC, garytate commented on plugins/containers/entities/entities/ix_container.lua
> +				bMultipleUsers = true,
Why has this been added?

2023-02-24 09:59 UTC, garytate commented on plugins/containers/entities/entities/ix_container.lua
>  					ix.log.Add(activator, "closeContainer", name, inventory:GetID())
```suggestion
					if (definition.OnClose) then
                        definition.OnClose(self, activator)
                    end
                    
					ix.log.Add(activator, "closeContainer", name, inventory:GetID())
```

2023-02-24 09:59 UTC, garytate commented on plugins/containers/entities/entities/ix_container.lua
> +					if def.OnOpen then
```suggestion
					if (definition.OnOpen) then
					    definition.OnOpen(self, activator)
					end
```

2023-04-26 18:27 UTC, alexgrist approved these changes

2023-05-08 19:04 UTC, merged